language: python
dist: xenial

addons:
  sonarcloud:
    organization: "ezhov-evgeny"
    token: f0f714f3bea6bd103e3eb82724ef3bb0d3b54d1d

services:
  - docker

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - docker pull bytemark/webdav
  - docker run -d --name webdav -e AUTH_TYPE=Basic -e USERNAME=alice -e PASSWORD=secret1234 -p 8585:80 bytemark/webdav
  - docker ps -a

install:
  - python setup.py develop
  - pip install coverage
script:
  - coverage run setup.py test
  - coverage xml
  - |
    if [[ $TRAVIS_PYTHON_VERSION == "3.8" ]]; then
      sonar-scanner
    fi
